### ISSUE TITLE
convert api calls to general browses to allow sorting and additional filtering

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#3949]
When using the general api browse style methods (usually plural class names $(name)sMethod) we should convert these to browses

This will allow standard filter and sorting based on the UI browsing. and will also reduce the complexity of managing these methods with custom functions.

## todo

- [x] the api methods need to allow additional filtering on top of the browse filters required for the methods (e.g. albums filtered by artist must allow additional album filters)
- [x] sort 'name'/'title' by default for all methods and allow all possible sorts
- [x] Methods with multiple types must use browse for all possible object types
- [x] ensure multi-artist is checked for all objects (e.g don't use song.artist, use artist_map)

## browse with cond and sort

- [x] album_songs (songs filtered by album)
- [x] albums
- [x] artist_albums (albums filtered by artist)
- [x] artist_songs (songs filtered by artist)
- [x] artists
- [x] browse (**multiple types**)
- [x] catalogs
- [x] followers
- [x] genre_albums (albums filtered by genre)
- [x] genre_artists (artists filtered by genre)
- [x] genre_songs (songs filtered by genre)
- [x] genres
- [x] get_indexes (**multiple types**)
- [x] index (**multiple types**)
- [x] label_artists (artists filtered by label)
- [x] labels
- [x] license_songs (songs filtered by license)
- [x] licences
- [x] list (**multiple types**)
- [x] live_streams
- [x] playlists (allow filters of combined playlist_search and playlist)
- [x] podcast_episodes
- [x] podcasts
- [x] shares
- [x] songs
- [x] stats (**multiple types** browse is used for random results only)
- [x] user_playlists (playlists filtered by user)
- [x] user_smartlists (smartlists filtered by user)
- [x] users
- [x] videos

## has browse missing cond and sort

- [x] none

## missing browse

- [ ] deleted_podcast_episodes
- [ ] deleted_songs
- [ ] deleted_videos
- [ ] last_shouts
- [ ] system_preferences (probably skip)
- [ ] user_preferences (probably skip)

## odd ones

- [ ] playlist_songs (songs filtered by playlist) (getting items for searches may not work for filtering or sorting)
- [x] localplay_songs (you have to call the localplay server so this probably can't be done)
- [ ] search_songs (runs a search, search is only rand() or name)
- [ ] bookmarks (no query)

## documentation for browse filters and sorts

- [ ] add browse information to ampache.org/api
- [ ] Add links to the browse docs for related methods so people can find them
- [ ] document browse filters
- [ ] document browse sorts
